van gijs
HonkingGoose/molveno_video_app pull request #37
Opened 2020-03-30 09:39 UTC by Gijs123

contact form

2020-03-30 10:24 UTC, HonkingGoose requested changes

2020-03-30 10:24 UTC, HonkingGoose commented on resources/views/contact/sentSuccessfully.blade.php
> +<h1> Your form has been sent successfully <h1>
I think a `<h2>` would be better here.

2020-03-30 10:24 UTC, HonkingGoose commented on resources/views/contact/form.blade.php
> +            <!-- <input type="hidden" name="action" id="action" value="Add" />
Is this commented out code needed later or not?

2020-03-30 10:24 UTC, HonkingGoose commented on app/Http/Controllers/ContactFormController.php
> +
Remove unnecessary white-space.

2020-03-30 12:41 UTC, mnk87 submitted a review, later dismissed

2020-03-30 12:45 UTC, HonkingGoose commented on resources/views/contact/sentSuccessfully.blade.php
> +<h1> Your form has been sent successfully <h1>
@mnk87 What do you think?

2020-03-30 12:57 UTC, HonkingGoose commented
@mnk87 We need to check if this works together with the new changes on `master`. I've pushed the changes from `master` into this branch.

2020-03-30 13:40 UTC, HonkingGoose requested changes
There is no input validation on the contact form.

Example:

- "First name": 123
- "Last name": 123
- "Room number": 1
- "Choose a category": complaint.
- "Message": This is a TEST.

This input is put in the database without any complaints or errors from Laravel or the database.

---

On the bright side, the contact form does work... 😄

2020-03-31 10:57 UTC, HonkingGoose approved these changes

2020-03-31 11:02 UTC, merged